### ISSUE TITLE
broken with Paper with CB packge relocation

### ISSUE THREAD

**Issue by YuanYuanOwO** [turikhay/MapModCompanion#117]
https://forums.papermc.io/threads/important-dev-psa-cb-package-relocation-will-be-removed.1106/   
Here is the error
```
[19:55:30 ERROR]: [EntrypointUtil] Encountered exception remapping plugins
java.lang.RuntimeException: Encountered exception remapping plugins
        at io.papermc.paper.pluginremap.PluginRemapper.waitForAll(PluginRemapper.java:274) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:163) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:42) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:105) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.Main.main(Main.java:131) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\MapModCompanion.jar'
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        ... 1 more
Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\MapModCompanion.jar'
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remapPlugin$0(PluginRemapper.java:226) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        ... 1 more
Caused by: java.lang.IllegalStateException: Duplicate entries detected: com/turikhay/mc/mapmodcompanion/shade/org/bstats/MetricsBase.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/charts/AdvancedBarChart.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/charts/AdvancedPie.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/charts/CustomChart.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/charts/DrilldownPie.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/charts/MultiLineChart.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/charts/SimpleBarChart.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/charts/SimplePie.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/charts/SingleLineChart.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/config/MetricsConfig.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/json/JsonObjectBuilder$1.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/json/JsonObjectBuilder$JsonObject.class, com/turikhay/mc/mapmodcompanion/shade/org/bstats/json/JsonObjectBuilder.class
        at net.minecraftforge.fart.internal.RenamerImpl.run(RenamerImpl.java:203) ~[paper-1.20.4.jar:?]
        at net.minecraftforge.fart.internal.RenamerImpl.run(RenamerImpl.java:94) ~[paper-1.20.4.jar:?]
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remapPlugin$0(PluginRemapper.java:223) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        ... 1 more
```

**Comment by turikhay** [comment]
Thanks for the heads up! The plugin should be working:

```
[00:46:46 INFO]: [PluginRemapper] Remapping plugin 'plugins/MapModCompanion.jar'...
[00:46:46 INFO]: [PluginRemapper] Done remapping plugin 'plugins/MapModCompanion.jar' in 57ms.
```

Nightly build is available: https://github.com/turikhay/MapModCompanion/actions/runs/8396591441/artifacts/1351461159
